version = 1

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "cxx"

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "scala"

[[transformers]]
name = "rustfmt"

[[transformers]]
name = "clang-format"

[[transformers]]
name = "autopep8"

[[transformers]]
name = "yapf"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"

[[transformers]]
name = "scalafmt"